# conda
pip=20.0.2
python=3.8.3
pandas
scikit-learn
matplotlib
seaborn
jupyter
keras
xlrd>=1.0.0

# pip, or conda-forge
python-dotenv
opencv-python
pydicom

#Pillow is a popular Python imaging library that can handle the decompression of
#some JPEG and JPEG2000 images. -- >easier than GDCM
pillow
# or
#conda install -c conda-forge openjpeg jpeg

# Instead of pillow, GDCM can be used
#GDCM is a C++ library for working with DICOM datasets that can decompress
#JPEG, JPEG-LS and JPEG2000 images.
#conda install gdcm -c conda-forge
